spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/contactdb
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true

  sql:
    init:
      mode: always
      platform: postgresql
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB

  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 3600000

server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    path: /user/error
    whitelabel:
      enabled: false
